### ISSUE TITLE
error

### ISSUE THREAD

**Issue by cosmos45** [dsantos-1/tinder-image-downloader#1]
im getting this error
please help me with this issue

**Traceback (most recent call last):
  File "tinder-img-downloader.py", line 73, in <module>
    fname=p['url'].split('/')[-1]
KeyError: 'url'**

**Comment by dsantos-1** [comment]
Hello, @cosmos45 ! I am sorry for the delayed response. I wasn't notified that you have opened an issue. Unfortunately the development team at Tinder fixed the vulnerability, so this script no longer works.
